[package]
name = "clap_host"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
generic_daw_utils = { path = "../generic_daw_utils" }

async-channel = "2.3.1"
clack-extensions = { git = "https://github.com/prokopyl/clack.git", features = [
    "audio-ports",
    "clack-host",
    "gui",
    "log",
    "note-ports",
    "params",
    "raw-window-handle_06",
    "state",
    "timer",
] }
clack-host = { git = "https://github.com/prokopyl/clack.git" }
dpi = "0.1.1"
home = "0.5.11"
raw-window-handle = "0.6.2"
walkdir = "2.5.0"
tracing = { version = "0.1.41", default-features = false, features = ["std"] }

[target.'cfg(target_os = "windows")'.dependencies]
etcetera = "0.8.0"
