[package]
name = "generic_daw_project"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"

[lints]
workspace = true
