version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/generic-front"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/generic-back"
    schedule:
      interval: "daily"
