[package]
name = "generic-daw"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
atomic_enum = "0.3.0"
clack-host = { git = "https://github.com/prokopyl/clack.git" }
cpal = "0.15.3"
generic-clap-host = { git = "https://github.com/generic-daw/generic-clap-host" }
hound = "3.5.1"
iced = { git = "https://github.com/iced-rs/iced", features = ["canvas"] }
iced_aw = { git = "https://github.com/iced-rs/iced_aw", features = [
    "number_input",
] }
itertools = "0.13.0"
rfd = "0.14.1"
rubato = "0.15.0"
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }

[lints.rust]
unused_crate_dependencies = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
enum_variant_names = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
similar_names = "allow"
struct_field_names = "allow"

allow_attributes = "warn"

[profile.release]
lto = true
codegen-units = 1
