[package]
name = "generic-daw"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clack-extensions = { git = "https://github.com/prokopyl/clack.git", features = [
    "clack-host",
    "gui",
    "raw-window-handle_06",
] }
clack-host = { git = "https://github.com/prokopyl/clack.git" }
cpal = "0.15.3"
dirs = "5.0.1"
hound = "3.5.1"
iced = { version = "0.12.1", features = ["canvas"] }
itertools = "0.13.0"
rfd = "0.14.1"
rubato = "0.15.0"
symphonia = { version = "0.5.4", features = ["all-formats", "all-codecs"] }
walkdir = "2.5.0"
winit = "0.30.5"
wmidi = "4.0.10"

[lints.rust]
unused_crate_dependencies = "warn"
dead_code = "allow"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
enum_variant_names = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
struct_field_names = "allow"

[profile.release]
lto = true
codegen-units = 1
