[package]
name = "generic-daw"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.89"
atomic_enum = { version = "0.3.0", default-features = false }
cpal = "0.15.3"
generic-clap-host = { git = "https://github.com/generic-daw/generic-clap-host", features = [
    "gui",
] }
hound = "3.5.1"
iced = { version = "0.13.1", default-features = false, features = [
    "advanced",
    "auto-detect-theme",
    "canvas",
    "wgpu",
] }
iced_aw = { version = "0.11.0", default-features = false, features = [
    "number_input",
] }
iced_fonts = { version = "0.1.1", features = ["bootstrap"] }
iced_wgpu = { version = "0.13.5", features = ["geometry"] }
include_data = "1.0.1"
itertools = "0.13.0"
rfd = "0.15.0"
rubato = { version = "0.16.0", default-features = false }
strum = { version = "0.26.3", features = ["derive"] }
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }

[lints.rust]
let-underscore = "warn"
missing-copy-implementations = "warn"
missing-debug-implementations = "warn"
rust-2018-idioms = "warn"
rust-2024-compatibility = "warn"
unused_crate_dependencies = "warn"
unused_qualifications = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
module_name_repetitions = "allow"

nursery = { level = "warn", priority = -1 }
missing-const-for-fn = "allow"

allow_attributes = "warn"
as_underscore = "warn"
assertions_on_result_states = "warn"
dbg_macro = "warn"
get_unwrap = "warn"
lossy_float_literal = "warn"
needless_raw_strings = "warn"
non_ascii_literal = "warn"
print_stdout = "warn"
print_stderr = "warn"
semicolon_inside_block = "warn"
separated_literal_suffix = "warn"
str_to_string = "warn"
string_lit_chars_any = "warn"
try_err = "warn"

[profile.release]
lto = true
codegen-units = 1
