[package]
name = "generic_daw_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
audio_graph = { path = "../audio_graph" }
clap_host = { path = "../clap_host" }
generic_daw_utils = { path = "../generic_daw_utils" }

arc-swap = "1.7.1"
async-channel = "2.3.1"
atomig = { git = "https://github.com/edwloef/atomig.git", branch = "update-syn-2", features = [
    "derive",
] }
cpal = "0.15.3"
hound = "3.5.1"
itoa = "1.0.15"
log = "0.4.27"
oneshot = "0.1.11"
rubato = { version = "0.16.2", default-features = false }
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }
