[package]
name = "generic_daw_core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
audio_graph = { path = "../audio_graph" }
clap_host = { path = "../clap_host" }

atomig = { version = "0.4.2", features = ["derive"] }
cpal = "0.15.3"
rubato = { version = "0.16.1", default-features = false }
strum = { version = "0.27.0", features = ["derive"] }
symphonia = { version = "0.5.4", features = ["all", "opt-simd"] }
rtrb = "0.3.2"
arraydeque = "0.5.1"
