[package]
name = "generic_daw"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
generic_daw_core = { path = "../generic_daw_core" }

home = "0.5.11"
iced = { version = "0.13.1", default-features = false, features = [
    "advanced",
    "canvas",
    "tokio",
    "wgpu",
] }
iced_aw = { version = "0.11.0", default-features = false, features = [
    "number_input",
] }
iced_file_tree = "0.3.0"
iced_fonts = { version = "0.1.1", features = ["bootstrap"] }
iced_wgpu = { version = "0.13.5", features = ["geometry"] }
itoa = "1.0.14"
rfd = "0.15.2"
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt"] }
