[package]
name = "generic_daw"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
generic_daw_core = { path = "../generic_daw_core" }
generic_daw_utils = { path = "../generic_daw_utils" }

async-channel = "2.3.1"
bit-set = "0.8.0"
dirs = "6.0.0"
dragking = { git = "https://github.com/edwloef/dragking.git", branch = "generic-daw" }
env_logger = "0.11.7"
fragile = "2.0.1"
iced = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", default-features = false, features = [
    "advanced",
    "canvas",
    "lazy",
    "svg",
    "tokio",
    "wgpu",
] }
iced_wgpu = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", features = [
    "geometry",
] }
infer = { version = "0.19.0", default-features = false }
itoa = "1.0.15"
log = "0.4.27"
oneshot = "0.1.11"
rfd = { version = "0.15.3", default-features = false, features = [
    "tokio",
    "xdg-portal",
] }
rtrb = "0.3.2"
tokio = { version = "1.44.1", features = ["rt", "time"] }
