[package]
name = "generic_daw"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
generic_daw_core = { path = "../generic_daw_core" }
generic_daw_project = { path = "../generic_daw_project" }
generic_daw_utils = { path = "../generic_daw_utils" }

arc-swap = "1.7.1"
bit-set = "0.8.0"
dirs = "6.0.0"
dragking = { git = "https://github.com/edwloef/dragking.git", branch = "generic-daw" }
env_logger = "0.11.8"
fragile = "2.0.1"
iced = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", default-features = false, features = [
    "advanced",
    "canvas",
    "smol",
    "svg",
    "wgpu",
    "x11",
] }
iced_wgpu = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", features = [
    "geometry",
] }
infer = { version = "0.19.0", default-features = false }
log = "0.4.27"
oneshot = "0.1.11"
rfd = "0.15.3"
smol = "2.0.2"
walkdir = "2.5.0"
