[package]
name = "generic_daw"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
generic_daw_core = { path = "../generic_daw_core" }
generic_daw_utils = { path = "../generic_daw_utils" }

fragile = "2.0.0"
hound = "3.5.1"
iced = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", default-features = false, features = [
    "advanced",
    "canvas",
    "svg",
    "tokio",
    "wgpu",
] }
iced_wgpu = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", features = [
    "geometry",
] }
infer = "0.19.0"
itoa = "1.0.15"
rfd = "0.15.2"
tokio = { version = "1.43.0", features = ["rt"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
