[package]
name = "generic_daw"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
generic_daw_core = { path = "../generic_daw_core" }
generic_daw_utils = { path = "../generic_daw_utils" }

bit-set = "0.8.0"
fragile = "2.0.0"
hound = "3.5.1"
iced = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", default-features = false, features = [
    "advanced",
    "canvas",
    "svg",
    "tokio",
    "wgpu",
] }
iced_wgpu = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", features = [
    "geometry",
] }
infer = { version = "0.19.0", default-features = false }
itoa = "1.0.15"
rfd = { version = "0.15.3", default-features = false, features = [
    "tokio",
    "xdg-portal",
] }
tokio = { version = "1.44.1", features = ["rt", "time"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
