[package]
name = "audio_graph"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
generic_daw_utils = { path = "../generic_daw_utils" }

atomig = "0.4.2"
bit-set = "0.8.0"
