[package]
name = "audio_graph"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ahash = "0.8.11"
atomig = "0.4.2"
downcast-rs = "2.0.1"

[lints]
workspace = true
